# Generated by Django 2.0.5 on 2018-05-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course of')),
                ('code', models.CharField(max_length=6, verbose_name='Course Code')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Software-1', 'Software First Semester'), ('Software-2', 'Software Second Semester'), ('Software-3', 'Software Third Semester'), ('Software-4', 'Software Fourth Semester'), ('Software-5', 'Software Fifth Semester'), ('Software-6', 'Software Sixth Semester'), ('Software-7', 'Software Seventh Semester'), ('Software-8', 'Software Eight Semester'), ('IT-1', 'IT First Semester'), ('IT-2', 'IT Second Semester'), ('IT-3', 'IT Third Semester'), ('IT-4', 'IT Fourth Semester'), ('IT-5', 'IT Fifth Semester'), ('IT-6', 'IT Sixth Semester'), ('IT-7', 'IT Seventh Semester'), ('IT-8', 'IT Eight Semester'), ('Computer-1', 'Computer First Semester'), ('Computer-2', 'Computer Second Semester'), ('Computer-3', 'Computer Third Semester'), ('Computer-4', 'Computer Fourth Semester'), ('Computer-5', 'Computer Fifth Semester'), ('Computer-6', 'Computer Sixth Semester'), ('Computer-7', 'Computer Seventh Semester'), ('Computer-8', 'Computer Eight Semester'), ('ELX-1', 'ELX First Semester'), ('ELX-2', 'ELX Second Semester'), ('ELX-3', 'ELX Third Semester'), ('ELX-4', 'ELX Fourth Semester'), ('ELX-5', 'ELX Fifth Semester'), ('ELX-6', 'ELX Sixth Semester'), ('ELX-7', 'ELX Seventh Semester'), ('ELX-8', 'ELX Eight Semester'), ('CIVIL-1', 'CIVIL First Semester'), ('CIVIL-2', 'CIVIL Second Semester'), ('CIVIL-3', 'CIVIL Third Semester'), ('CIVIL-4', 'CIVIL Fourth Semester'), ('CIVIL-5', 'CIVIL Fifth Semester'), ('CIVIL-6', 'CIVIL Sixth Semester'), ('CIVIL-7', 'CIVIL Seventh Semester'), ('CIVIL-8', 'CIVIL Eight Semester'), ('GS-1', 'GS First Semester'), ('GS-2', 'GS Second Semester'), ('GS-3', 'GS Third Semester'), ('GS-4', 'GS Fourth Semester'), ('GS-5', 'GS Fifth Semester'), ('GS-6', 'GS Sixth Semester'), ('GS-7', 'GS Seventh Semester'), ('GS-8', 'GS Eight Semester'), ('BCA-1', 'BCA First Semester'), ('BCA-2', 'BCA Second Semester'), ('BCA-3', 'BCA Third Semester'), ('BCA-4', 'BCA Fourth Semester'), ('BCA-5', 'BCA Fifth Semester'), ('BCA-6', 'BCA Sixth Semester'), ('BCA-7', 'BCA Seventh Semester'), ('BCA-8', 'BCA Eight Semester')], max_length=20)),
            ],
            options={
                'verbose_name': 'Department and Semester',
                'verbose_name_plural': 'Departments and Semesters',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_of', models.CharField(choices=[('ST', 'Science And Technology')], max_length=2, verbose_name='Faculty of ')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Course')),
            ],
            options={
                'verbose_name': 'Resource Item',
                'verbose_name_plural': 'Resource Items',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept_sem',
            field=models.ManyToManyField(to='resources.DeptSem'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Faculty'),
        ),
    ]
