# Generated by Django 2.0.5 on 2018-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourceurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceurl',
            name='title',
            field=models.CharField(default='Nischal', max_length=100),
            preserve_default=False,
        ),
    ]
