# Generated by Django 2.0.5 on 2018-05-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resourceitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='slug',
            field=models.SlugField(default='Hello-world'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceurl',
            name='slug',
            field=models.SlugField(default='Hello-world'),
            preserve_default=False,
        ),
    ]
